baseURL = "/"
languageCode = "en-us"
title = "Project 1 Docs"
theme = "ananke"

[[menu.main]]
name = "Docs"
url = "/docs/"
weight = 10

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 20
